# Generated by Django 4.2.7 on 2024-01-15 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userresult',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voting'),
        ),
        migrations.AddField(
            model_name='question',
            name='bulletin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.bulletin'),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.questiontype'),
        ),
        migrations.AddField(
            model_name='memberslist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memberslist',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voting'),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='voting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.voting'),
        ),
        migrations.AddField(
            model_name='anonymresult',
            name='anonym',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.anonym'),
        ),
        migrations.AddField(
            model_name='anonymresult',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voting'),
        ),
        migrations.AddField(
            model_name='anonym',
            name='voting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.voting'),
        ),
        migrations.AlterUniqueTogether(
            name='userresult',
            unique_together={('voting', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='anonymresult',
            unique_together={('voting', 'anonym')},
        ),
    ]
