# Generated by Django 4.2.7 on 2024-03-29 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userparticipant',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voting'),
        ),
        migrations.AddField(
            model_name='userbulletinanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.answer'),
        ),
        migrations.AddField(
            model_name='userbulletinanswer',
            name='bulletin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bulletin'),
        ),
        migrations.AddField(
            model_name='userbulletinanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='voting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.voting'),
        ),
        migrations.AddField(
            model_name='answer',
            name='bulletin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bulletin'),
        ),
        migrations.AddField(
            model_name='anonymbulletinanswer',
            name='anonym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.anonym'),
        ),
        migrations.AddField(
            model_name='anonymbulletinanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.answer'),
        ),
        migrations.AddField(
            model_name='anonymbulletinanswer',
            name='bulletin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bulletin'),
        ),
        migrations.AddField(
            model_name='anonym',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voting'),
        ),
        migrations.AlterUniqueTogether(
            name='userparticipant',
            unique_together={('voting', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='userbulletinanswer',
            unique_together={('bulletin', 'answer')},
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('text', 'bulletin')},
        ),
        migrations.AlterIndexTogether(
            name='answer',
            index_together={('text', 'bulletin')},
        ),
        migrations.AlterUniqueTogether(
            name='anonymbulletinanswer',
            unique_together={('bulletin', 'answer')},
        ),
    ]
