# Generated by Django 4.2.7 on 2023-12-19 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_anonymresult_voting_alter_userresult_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='data_of_birth',
            new_name='date_of_birth',
        ),
    ]
