# Generated by Django 4.2.7 on 2024-05-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='status',
            field=models.CharField(choices=[('nonactive', 'Неактивно'), ('active', 'Активно'), ('finished', 'Завершено')], default='nonactive', max_length=9),
        ),
    ]
