# Generated by Django 4.2.7 on 2024-01-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonym',
            name='code',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
    ]
