# Generated by Django 4.2.7 on 2024-05-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_voting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='actual_voters_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
